In [1]:
import numpy as np

In [2]:
boards_string = '''22 13 17 11  0
 8  2 23  4 24
21  9 14 16  7
 6 10  3 18  5
 1 12 20 15 19

 3 15  0  2 22
 9 18 13 17  5
19  8  7 25 23
20 11 10 24  4
14 21 16 12  6

14 21 17 24  4
10 16 15  9 19
18  8 23 26 20
22 11 13  6  5
 2  0 12  3  7'''

number_sequence_str = '''7,4,9,5,11,17,23,2,0,14,21,24,10,16,13,6,15,25,12,22,18,20,8,19,3,26,1'''

Split this into steps
Want to make each board into a numpy array of values

1. split boards string into distinct boards and convert to numbers 
2. swap matching numbers with letters one at a time
3. 

In [3]:
def parse_boards(inp_board: str) -> list:
    '''
    Splits a string of numbers into distinct boards as numpy arrays
    '''
    boards_split = inp_board.split('\n\n')
    
    # Splits rows into distinct strings and appends rows to 'boards' in a list
    boards = []
    for row in boards_split:
        boards.append(row.split('\n'))
        
    int_boards = []
    for each_board in boards:
        board = []
        for each_row in each_board:
            row = [int(i) for i in each_row.split()]
            board.append(row)
        int_boards.append(np.array(board).reshape(5,5))
    
    return int_boards
    
    
def value_replace(boards: list, value: int)-> list:
    iterated_boards = []
    for each_arr in boards:
        replaced_board = np.where(each_arr == value, -1 ,each_arr)
        iterated_boards.append(replaced_board)
        
    return iterated_boards


def win_check(board):
    
    row_sum = np.sum(board, axis = 1) # summing across rows
    col_sum = np.sum(board, axis = 0) # summing across cols
    
    if -5 in row_sum:
        return True
    if -5 in col_sum:
        return True
    return False

In [4]:
# Part 1 solution
boards = parse_boards(boards_string)
print(boards)

for i in [int(x) for x in number_sequence_str.split(',')]:
    boards = value_replace(boards, i)
    for board in boards:
        if win_check(board):
            board = np.where(board == -1, 0 ,board)
            _sum = np.sum(board)
            print(_sum*i)
            break
    else:
        continue #jumps to top if for-loop not broken out of
        
    break
        

[array([[22, 13, 17, 11,  0],
       [ 8,  2, 23,  4, 24],
       [21,  9, 14, 16,  7],
       [ 6, 10,  3, 18,  5],
       [ 1, 12, 20, 15, 19]]), array([[ 3, 15,  0,  2, 22],
       [ 9, 18, 13, 17,  5],
       [19,  8,  7, 25, 23],
       [20, 11, 10, 24,  4],
       [14, 21, 16, 12,  6]]), array([[14, 21, 17, 24,  4],
       [10, 16, 15,  9, 19],
       [18,  8, 23, 26, 20],
       [22, 11, 13,  6,  5],
       [ 2,  0, 12,  3,  7]])]
4512


# Part 2

In [5]:
#Part 2: want to do the same but for the last to win

boards = parse_boards(boards_string)

won_boards = [] #Keep track of won boards
for i in [int(x) for x in number_sequence_str.split(',')]:
    boards = value_replace(boards, i)
    for n, board in enumerate(boards):
        if n in won_boards:
            continue
        elif win_check(board):
            won_boards.append(n)
    if len(won_boards) == 3:
        break



last_board = boards[won_boards.pop()]
last_board = np.where(last_board == -1, 0 ,last_board)

print('last board to win\n', last_board)

print('\nanswer = ',i*np.sum(last_board))

last board to win
 [[ 3 15  0  0 22]
 [ 0 18  0  0  0]
 [19  8  0 25  0]
 [20  0  0  0  0]
 [ 0  0  0 12  6]]

answer =  1924
